sudo: required

language: java

services:
- docker

jdk:
- oraclejdk8

script:
- "./gradlew test --info --stacktrace"

after_success:
  - docker login -e "${DOCKER_EMAIL}" -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
  - |
    if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      $( cd docker && ./build.sh latest && ./push.sh latest )
    else
      echo "Not on master (or current build is a PR) - skipping Docker build"
    fi
