sudo: required

language: java

services:
- docker

jdk:
- oraclejdk8

script:
- "./gradlew test shadowJar --info --stacktrace"

after_success:
  - |
    set -e
    case "${TRAVIS_BRANCH}" in
      master)
        IMAGE_TAG="latest"
        ;;
      develop)
        IMAGE_TAG="beta"
        ;;
    esac
    if [ ! -z "${IMAGE_TAG}" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      echo "Releasing image: ${IMAGE_TAG}"
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
      cd ./docker
      ./build.sh "${IMAGE_TAG}"
      ./push.sh "${IMAGE_TAG}"
    else
      echo "Not on release branch (or current build is a PR) - skipping Docker build"
    fi
