sudo: required

language: java

services:
- docker

jdk:
- oraclejdk8

script:
- "./gradlew test --info --stacktrace"

after_success:
  - ./gradlew shadowJar --info --stacktrace
  - docker login -e "${DOCKER_EMAIL}" -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
  - |
    set -e
    if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      cd ./docker
      ./build.sh latest
      ./push.sh latest
    else
      echo "Not on master (or current build is a PR) - skipping Docker build"
    fi
